services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zea-board-backend
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zea-board-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
